[phases.setup]
nixPkgs = ["python312", "ffmpeg", "libopus", "opusfile", "libogg"]

[phases.install]
cmds = [
    "python3 -m venv /opt/venv",
    ". /opt/venv/bin/activate",
    "pip install -r requirements.txt"
]

[start]
cmd = "python3 discord_multibot.py"
